### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by weatherguyto** [romankisil/eqMac2#13]
Hello,

On the drop down on the menu on eqMac2 has the control for the tones, can you put the volume control there too, as my system volume on the menubar is grayed out, and when I need to control the volume right away, I would like it to easy access from the eqMac2 drop down menu that show up.

Thanks
![volume_control](https://user-images.githubusercontent.com/6969157/28721024-e130dec2-737c-11e7-86d5-03ac5717e9fb.jpg)

**Comment by romankisil** [comment]
You can access the volume control from the second (Settings) menu?

**Comment by weatherguyto** [comment]
Hello,

Yes, but to many steps to access quickly.

Thanks

**Comment by romankisil** [comment]
You can use Volume control buttons as well (F11, F12) or you are on the new Macbook Pro with Touchbar?

**Comment by cbornhoft** [comment]
Great work on the new version @romankisil!

I can confirm, touchbar controls are greyed out and do not work with eqMac2. Have to go into the app menu and change it from there. It's disabled everywhere else.

**Comment by romankisil** [comment]
@cbornhoft yeah it's because, to make eqMac2 device invisible when app is not running, I had to make it invisible by default. But to make it visible again, I have to create an aggregate audio device and add eqMac2 device to it. Aggregate Devices in OSX don't support volume controls :( I know a way that Boom3D managed to have device invisible and have volume controls, it's just a bit of work to rewrite the logic of the app to support that. Maybe soon

**Comment by cbornhoft** [comment]
That makes sense, thanks for the explanation 👍

**Comment by romankisil** [comment]
Can do much without cluttering the UI of the EQ menu. Someone needs to come up with a UX design first.

**Comment by rstudner** [comment]
Just to comment.  I installed eqmac2 and my MAX volume is MUCH lower than before.

I have everything maxed out, and it is at least 50% quieter than if I remove eqmac2.

is this known/expected?

**Comment by PotusThePlant** [comment]
@rstudner I don't know how you have it set up but given that the preamp gain isn't shown, it must automatically decrease so that's probably why your volume is lower. This is necessary to avoid distortion.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
