### ISSUE TITLE
Update README && Code Conduct

### ISSUE THREAD

**Issue by romankisil** [romankisil/eqMac2#15]
Still haven't implemented a README and code conduct.

**Comment by romankisil** [comment]
![eqmacdiagram](https://user-images.githubusercontent.com/8472525/29003031-13d1cd60-7aa7-11e7-9868-6afc36a34b52.jpg)

**Comment by romankisil** [comment]
<img width="193" alt="screen shot 2017-08-06 at 13 31 55" src="https://user-images.githubusercontent.com/8472525/29003276-ba3030c6-7aab-11e7-8529-206129e99a2c.png">
![Uploading Screen Shot 2017-08-06 at 13.32.20.png…]()

**Comment by romankisil** [comment]
<img width="149" alt="screen shot 2017-08-06 at 13 31 55" src="https://user-images.githubusercontent.com/8472525/29003295-fa4f92f0-7aab-11e7-9b5d-9ff2fbc7f845.png">
<img width="147" alt="screen shot 2017-08-06 at 13 32 20" src="https://user-images.githubusercontent.com/8472525/29003296-fa5602c0-7aab-11e7-8180-6b641dd27693.png">

**Comment by romankisil** [comment]
<img width="383" alt="screenshot" src="https://user-images.githubusercontent.com/8472525/29582045-27cbf68c-8773-11e7-8490-8fbc6eaea743.png">

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
