### ISSUE TITLE
MBP Touchbar - No Volume Control

### ISSUE THREAD

**Issue by iMagic16** [romankisil/eqMac2#19]
Hi,

Since EQM2 release I've been unable to control the volume - it is constantly at a blistering loud volume and every time I try to switch to standard output to adjust it automatically swaps back - in the menu bar or at system settings

Pic1:
![image](https://user-images.githubusercontent.com/4530346/28831542-ba075026-76d1-11e7-97ec-d00ba36e6980.png)

Touchbar:
![image](https://user-images.githubusercontent.com/4530346/28831531-b15a8970-76d1-11e7-8557-0224e996cd02.png)

Can you (as a temp fix) disable the auto-swapping and preferably as a long term fix, allow volume control via touch-bar or OS menu, or within eqMac as was the case in eqMac1 (separate slider to the left)

other than that, good app!

**Comment by iMagic16** [comment]
Would it be possible to get an eqMac1 download as a temp fix? I need the volume control more than I need universal device support atm 👍

**Comment by romankisil** [comment]
@iMagic16 you can adjust the volume by right clicking on the eqMac2 icon in the menubar :)

**Comment by romankisil** [comment]
@iMagic16 I will update the website today to include the download link to the old eqMac

**Comment by romankisil** [comment]
@iMagic16 in fact here you go: https://www.dropbox.com/s/zj9a9ao9xe6250e/eqMac.dmg?dl=1

**Comment by iMagic16** [comment]
the right click feature doesn't seem to work for me using the option-click method but works with 2 finger mouse click, thanks for sharing that!

Keep up the good work & thanks!

**Comment by romankisil** [comment]
I have creates Issue #24 to fix the Option-click method of opening the settings menu. Will close this issue for now, until I figure out how to redo the Audio Device

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
