### ISSUE TITLE
Bluetooth vs 3.5mm, sound seems a little distorted over BT

### ISSUE THREAD

**Issue by computer1up** [romankisil/eqMac2#47]
When I connect my wireless headphones (Skullcandy Hesh 2 Wireless) over Bluetooth, I have to be very careful when adjusting the bass-frequencies. Too much and the entire bass will sound distorted. This problem is not present when I connect the same headphones with an audio cable to my Mac. 

My headphones sound normal when connected via BT to my iPhone, cranking up the bass works without any problems on that device. 

Is this an issue with the app or am I doing something wrong? Version is eqMac2 2.0.6

**Comment by romankisil** [comment]
I did manage to replicate what you described. I am not sure why this is happening, but in my case only one of 2 BT devices does this. I Assume it has something to do with frequency differences between device. Will have to look into it eventually, but only after I make a switch to another audio driver (described in #51 )

**Comment by computer1up** [comment]
Who knows, maybe switching to another driver actually solves this, haha!

**Comment by computer1up** [comment]
I'm currently checking out the paid app Boom2 in its trial form, just to compare. I'm more or less having the same problem with that app too, so maybe it's some kind of issue with the bluetooth drivers instead of your app. Honestly, I like eqMac2 more since it's opensource and doesn't cost any money, though.

**Comment by MiLeung** [comment]
Same problem. I get a lot of distortion in the bass when I boost it using an Amazon Echo or Google Home, but works fine with wired earbuds.

No distortion in the bass when I make it lower than normal though.

**Comment by romankisil** [comment]
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by computer1up** [comment]
Giving it a quick try, it seems that there's much less distortion, if at all. I'll try it more extensively tomorrow.

**Comment by computer1up** [comment]
I noticed one more thing with this new version: when I turn the Mac's volume to the maximum, even though my headphones aren't maxed out on volume, the sound gets extremely distorted. This is not dealbreaking though, I get plenty of volume out of them without max volume on my Mac, but this might be worth noting.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
