### ISSUE TITLE
Move to Virtual Audio Driver based on Audio Server Plug-In

### ISSUE THREAD

**Issue by romankisil** [romankisil/eqMac2#51]
This will bring more control into adjusting volume and hiding the device properly. 
Boom3D uses similar driver they wrote in house for this. Here's an open message I found from one of their developers:
```
+
++ April 2015
++ Raveeshwara S
+

As per current findings, we could capture system audio via user-space virtual audio driver based on Audio Server Plug-In. There should be many other ways to capture system audio too.

Key differences with current technology:

* Driver resides in user space (as opposed to kernel space)
* AudioServerPlugIn drivers are officially supported with all sandboxed applications (as opposed to AudioHardwarePlugIn)
* Sandboxed - AudioServerPlugIn runs in a limited, minimalist environment

Might be possible:

* Once AudioServerPlugIn is loaded, it should be feasible to add / remove virtual audio device internally
* Application specific audio isolation
* User space plug-in could have XPC based communication with other processes (QA1811)

Usability:

A quick testing of our custom Audio Server Plug-In with CAPlaythrough, and Boom 2 seems working. However, further thorough testing with different conditions is required.

Known issues:

* Minor glitch with small duration sound. E.g.: Volume change feedback sound. This could be related to unused buffer space. Yet to start looking into this issue.

Installation:

An AudioServerPlugIn should be loaded into coreaudiod. We could achieve this in just two steps:

* Place plug-in in /Library/Audio/Plug-Ins/HAL
* Restart the computer

To place plug-in in library folder (/Library/Audio/Plug-Ins/HAL), we do require root (i.e., administrator) privilege.

After placing the plug-in in HAL folder, as an alternate for restarting computer, the following could also be used:

  Alternative 1:
* Log-out, log-in

  Alternative 2: (hard way)
* Stop coreaudiod and start it again
```

**Comment by romankisil** [comment]
Won't be implemented in eqMac2. Will be implemented in eqMac3 or whatever the next version will be called. Closing

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
