### ISSUE TITLE
Menubar-Item won't work sometimes

### ISSUE THREAD

**Issue by Arc3lore** [romankisil/eqMac2#54]
So, I'm using MacOS X El Capitan Version 10.11.6 on a MacBook Pro from late 2008.
My problem now is, that when I click on the menubar-item (in the menubar, obviously) the background of the logo turns dark-blue like it's supposed to when it's activated, but the menu where I can set the EQ-Mode like 'Rock' and other pre-made settings is not shown. 
To 'fix' that, I simply wait a moment (about 15 seconds or so) and click on it again. Usually it works then.
![working](https://user-images.githubusercontent.com/32132439/30645989-c2a59ab8-9e17-11e7-91b2-57dd779693a2.png)
![not working](https://user-images.githubusercontent.com/32132439/30645990-c2aa256a-9e17-11e7-8150-472ee2c63f0c.png)
![working 2](https://user-images.githubusercontent.com/32132439/30646039-eaecf656-9e17-11e7-93f4-d0a053a5306b.png)

**Comment by romankisil** [comment]
can you post a screenshot or a video describing the bug?

**Comment by artistbuddy** [comment]
I can confirm the same issue in previous versions too. It happen randomly. OS X 10.12.6

**Comment by romankisil** [comment]
Yes I have experience this as well at some point. Valid bug, should be fixed sometime in the future. For now just right click on the icon and then left click, which usually refreshes the click events and the menu works again

**Comment by seanthebean** [comment]
This happened to me on a fresh install (also running OS X 10.12.6). The right-click trick doesn't seem to be helping - at first the right-click menu would still come up, but then it stopped working as well. Please fix this bug soon so I can use your handy tool again. :)

**Comment by romankisil** [comment]
Should be fixed in PR #65 
Will be released with Build v2.1

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
