### ISSUE TITLE
Secondary menu hides after hanging and shows "problem connecting server" pop-up

### ISSUE THREAD

**Issue by lookfortheroot** [romankisil/eqMac2#57]
Version 2.0.7 on Sierra 10.12.5 with external DAC.

When I try to open secondary menu (with volume bar and buttons), menu item hangs with "ball" cursor and after 30-60 seconds, a pop-up appears: "There was a problem connecting to the server".

I tested earlier versions when my home server was online, now it is disconnected. For some reason eqMac wants to see my died server? ;)

Update: menu item is not just hangs, but the menu freezes too, so I can't use it.

**Comment by romankisil** [comment]
To be honest, I have no idea what are you talking about. I didn't know you can have some sort of a server :) Could you please sketch or explain in detail, what is your setup? Thanks

**Comment by lookfortheroot** [comment]
Sorry, under the server I mean ordinary old PC with Ubuntu under the desk :))
So it works 24/7, but now is temporarily offline by technical reasons.

**Comment by romankisil** [comment]
How is your PC with Ubuntu under the desk has anything to do with eqMac? I am very confused

**Comment by lookfortheroot** [comment]
Argh, sorry again, this is second PC. I work on **main** PC with Hackintosh ^_^

**Comment by romankisil** [comment]
I still don't understand how is this issue connected to eqMac. eqMac2 never tries to connect to any servers :)

**Comment by lookfortheroot** [comment]
And that is the point! My eqMac somehow works normally only when the server is online. I absolutely don't understand this magic too. 😭

**Comment by romankisil** [comment]
Sorry, I can't guarantee support for the Hackintosh platform :( Closing this issue

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
