### ISSUE TITLE
Equalizer band setting increase over saving multiple times

### ISSUE THREAD

**Issue by kevinra** [romankisil/eqMac2#59]
First of all, thanks for the great product! It is much better than original eqmac!

The bug I'm facing is that when I save eq setting multiple times, band settings increase slightly. I'm not sure it's only UI that's changing or the actual gain on that frequency changes but either way, it's a bug.

To reproduce:
1. Place a eq band around 75%. (Works regardless of how many bands are above 0 gain but modifying one band is sufficient to see the change. Also, it seems like higher the gain, the greater the effect.)
2. Save this eq multiple times (Things become more evident after 5-10 saves).
3. Compare the first saved eq and last saved eq.

I attached my image for reference.
<img width="294" alt="screen shot 2017-10-12 at 12 27 08 am" src="https://user-images.githubusercontent.com/6539629/31479302-3ee9718a-aee4-11e7-9d38-dfe379768052.png">
<img width="293" alt="screen shot 2017-10-12 at 12 27 16 am" src="https://user-images.githubusercontent.com/6539629/31479301-3edbc742-aee4-11e7-98f0-5822e908ad56.png">

Used build 2.0.6 (one from the website: https://bitgapp.com/eqmac)
Tested on 2016 MacBook Pro, 13 inch.
MacOS High Sierra (10.13)

**Comment by jakecoxux** [comment]
Can confirm bug also exists in v2.0.7 pre-release.

From memory, this bug may, or may not have been around since v2.0.5

![screen shot 2017-10-12 at 4 30 41 pm](https://user-images.githubusercontent.com/30495935/31480674-dcc97d88-af6a-11e7-859a-192de26d84f5.png)

High Sierra (10.13) - MacBook Air 13" - Early 2015

**Comment by romankisil** [comment]
Yeap, saw this bug too. Will try fix in next update :)

**Comment by romankisil** [comment]
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by romankisil** [comment]
Considering issue fixed as no one replied and issue is not seen anymore on my machine

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
