### ISSUE TITLE
BUG: App loses reference of Output Device when Mac is restarted 

### ISSUE THREAD

**Issue by romankisil** [romankisil/eqMac2#6]
Submitted by @jameyers4

> Using eqmac2 on my MacBook 2016 w/ touchbar (4 thunderbolt ports). Sierra 10.12.6. Works very well except when I restart the OS, my preferred bluetooth audio output device is not preserved, and requires manual intervention to restore audio output.

> Please let me know if I can provide further useful information.

**Comment by jameyers4** [comment]
Hi Roman - 

Silly question - once you get this fixed, were/how do I pick up a new build with the fix?

Best regards, 

Jeff

**Comment by romankisil** [comment]
@jameyers4 By clicking on "Check for Updates" in the eqMac2 Setting menu :)

**Comment by jameyers4** [comment]
LOL - silly me.  Being a software tester, I’m so accustomed to having to retrieve from a depot, install, etc….  

Holler if you need anything for my reported bug and enhancement.

Best, 

Jeff

**Comment by jameyers4** [comment]
So I can also say this - if music is playing well through my BT speakers using eqMac2 and I restart my Mac - it comes up not even knowing that the BT speakers are there until I go into sound preferences and re-attach to BT speakers.  This absolutely did not happen before I installed eqMac2 - before, the Mac would find the BT speakers on restart / boot.

**Comment by romankisil** [comment]
fixed in a31e2bc8c939d7a0b08daae8a31913b3e9b1e5b4

**Comment by jameyers4** [comment]
Great!  How much more work before next build comes along?  Thank you

**Comment by romankisil** [comment]
@jameyers4 not much. Maybe will push an update today or tomorrow morning (UK time)

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
