### ISSUE TITLE
can't use esc key to close eqMac2 dialog

### ISSUE THREAD

**Issue by jameyers4** [romankisil/eqMac2#7]
When I click on eqMac2 in the menu bar to change settings, I have to click on it a 2nd time to close the dialog.  Most/all other Mac programs that have a widget in the menu bar will allow the "esc" key to close the dialog.  Please consider this change for ease of use.

**Comment by jameyers4** [comment]
additional thought - would be nice (in addition to "esc" to be able to click outside eqMac2 dialog to dismiss per normal convention.

**Comment by sermshar** [comment]
another suggestion along the same lines: would be to keep the menubar unhidden (if it's set to autohide) while the eqMac menu is open.

I have my menu bar set to hide automatically, all of apple's menus keep the bar unhidden as long as they're open, but many third party menus stay open while the bar disappears and it looks weird. In the case of eqMac2, the bar disappears and the eqMac menu shifts up with it, which can be jarring, especially when I go to click a button but it moves up because my mouse isn't over the menu bar anymore. 

the escape-key/click-away feature would also be good for this because then I wouldn't have to bump the top of the screen > to open the menu bar > to click eqMac logo in order to close the menu.

**Comment by romankisil** [comment]
fixed in bb743ec3cd82c301ce620c17b23c87bac62cb923

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
