### ISSUE TITLE
Separate left and right channel equalization (feature request)

### ISSUE THREAD

**Issue by piccolbo** [romankisil/eqMac2#73]
I have a specific one sided, band specific, fluctuating hearing impairment that could be counterbalanced by boosting the bass on one side only. No application I know of allows to do this system wide. To make it sound less niche, consider rooms with poor acoustic properties, for instance when only one speaker has to be placed near a window, or when a wall opens to another room or what not. There's  many situations where the two channels require separate equalization. It's also not too difficult to do, by generating pure frequencies and tweaking the equalization curves until the sound appears to come from  the middle across the audible range.

 Can this be added to eqMac2? At what effort? Thanks

**Comment by romankisil** [comment]
This feature should be possible to implement, but at enormous effort. I Don't think eqMac will ever be able to split the EQ effect between channels. Sorry.

**Comment by MartyMaro** [comment]
I accept this is closed, however I have a hear impairment on my right side, too. Can't we do anything about it? Is there any alternative, then?

**Comment by catchke2ro** [comment]
> I accept this is closed, however I have a hear impairment on my right side, too. Can't we do anything about it? Is there any alternative, then?

I have the same issue, asymetric hearing. I've used menubus earlier, with an attached Stereo EQ VST. But that product has been discontinued. So now I'm finding the solution, this was a hope, but it seems not the solution. :(

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by piccolbo** [comment]
Since @nodeful announced the new version here, I assume it adds the feature requested herein. Or at least I can not imagine any other reason. On the other hand, he only announced a list of bugs and a tech stack, non remotely relevant to the feature discussed here. So what gives?

**Comment by nodeful** [comment]
I have added the same comment to every issue all 180 of them to make people aware that there's a new version and it might work better for them. Sorry if it was misleading. eqMac is still an open canvas and I am considering all features, just have to prioritise my time to the most common problems first. Some day I will get to this one as well. Cheers

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
