### ISSUE TITLE
Sound gradually deteriorates

### ISSUE THREAD

**Issue by Satori83** [romankisil/eqMac2#97]
So I run a 27" iMac with Sierra. Audio goes to a Focusrite 212 connected to Tannoy reference monitors. The sound is fins for about 45 mins or so and then it starts to slowly get distorted. Now, I can "reset" it by opening Sound prefs and just clicking on the Focusrite again. It goes right back to highlighting eqMac2, but for some reason clicking the other interface temporarily suspends the distortion. This happens regardless of audio source, browser, app, etc.

![image](https://user-images.githubusercontent.com/3317473/33144124-fefed332-cf89-11e7-8306-ef201358b396.png)

![image](https://user-images.githubusercontent.com/3317473/33144135-071825f0-cf8a-11e7-8dc6-ab5e16e7b963.png)
# #

**Comment by romankisil** [comment]
Thanks for the information, however, this issue has been reported already :) But again, thanks for additional info

**Comment by Satori83** [comment]
Really? Sorry I didnt see it. Can you send me link to that post?

Thanks,Scott Foster




Founder / Project Coordinator
Office: 215-478-8171 ext.1This e-mail message may contain confidential or
legally privileged information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution, copying
or the taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they can be
intercepted, amended, or contain viruses. Anyone who communicates with us by
e-mail is deemed to have accepted these risks. Satori Design is not responsible
for errors or omissions in this message and denies any responsibility for any
damage arising from the use of e-mail. Any opinion and other statement contained
in this message and any attachment are solely those of the author and do not
necessarily represent those of the company.







On Wed, Nov 22, 2017 3:08 PM, Roman Kisil notifications@github.com  wrote:
Thanks for the information, however, this issue has been reported already :) But
again, thanks for additional info

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
